name: smoke-windows-strawberryperl

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  strawberry-gmake:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        # see https://github.com/shogo82148/actions-setup-perl/blob/main/versions/strawberry.json
        perl-version:
          - "5.40"
          - "5.38"
          - "5.36"
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"

    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
          distribution: strawberry
      - name: target-setup-perl (perl -V)
        shell: bash
        run: |
            echo "::group::setup-perl (perl -V)"
            export MYPERL=$(which -a perl | grep -m 1 hostedtoolcache)
            echo "MYPERL=$MYPERL" >> $GITHUB_ENV
            $MYPERL -V
            echo "::endgroup::"
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
        with:
            fetch-depth: 10
      - name: Find out environment
        shell: bash
        run: |
          $MYPERL -MIPC::Cmd -E "say IPC::Cmd::can_run(qq{gcc})"
          $MYPERL -MIPC::Cmd -E "say IPC::Cmd::can_run(qq{g++})"
          $MYPERL -MIPC::Cmd -E "say IPC::Cmd::can_run(qq{ld})"
          $MYPERL -MIPC::Cmd -E "say IPC::Cmd::can_run(qq{gmake})"
      - name: Configure
        shell: bash
        run: |
            $MYPERL Makefile.PL
      - name: Build
        shell: cmd
        run: gmake
      - name: Run Tests
        shell: cmd
        run: gmake test
      - name: Run disttest
        shell: cmd
        run: gmake disttest NOECHO=

  strawberry-dmake:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.24"
          - "5.22"
          - "5.20"
          - "5.16"
          - "5.14"

    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
          distribution: strawberry
      - name: target-setup-perl (perl -V)
        shell: bash
        run: |
            echo "::group::setup-perl (perl -V)"
            export MYPERL=$(which -a perl | grep -m 1 hostedtoolcache)
            echo "MYPERL=$MYPERL" >> $GITHUB_ENV
            $MYPERL -V
            echo "::endgroup::"
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
        with:
            fetch-depth: 10
      - name: Find out environment
        shell: bash
        run: |
          $MYPERL -MIPC::Cmd -E "say IPC::Cmd::can_run(qq{gcc})"
          $MYPERL -MIPC::Cmd -E "say IPC::Cmd::can_run(qq{g++})"
          $MYPERL -MIPC::Cmd -E "say IPC::Cmd::can_run(qq{ld})"
          $MYPERL -MIPC::Cmd -E "say IPC::Cmd::can_run(qq{dmake})"
      - name: Configure
        shell: bash
        run: |
            $MYPERL Makefile.PL
      - name: Build
        shell: cmd
        run: dmake
      - name: Run Tests
        shell: cmd
        run: dmake test
      - name: Run disttest
        shell: cmd
        run: dmake disttest NOECHO=
